FROM node:20-buster As builder
WORKDIR /app
RUN npm install pnpm -g
COPY package.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
RUN NITRO_PRESET=node-server pnpm run build

FROM node:20-slim As runner
WORKDIR /app
COPY --from=builder /app/.output  ./.output
COPY --from=builder /app/package.json  ./package.json
COPY --from=builder /app/node_modules  ./node_modules

ENV PORT=3615
EXPOSE 3615

CMD ["node", ".output/server/index.mjs"]